name: infra_quant
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - seaborn
  - scipy
  - ipykernel
  - xarray
  - cdsapi
  - jupyter
  - pvlib-python
  - glpk
  - numpy
  - pandas
  - pyomo
  - openpyxl
  - netcdf4
  - matplotlib
  - highs
  - highspy
  - scikit-learn
  - python-dotenv
  - dask
  - numpy-financial
  - pydantic
  - pydantic-settings
  - salib
  - h5netcdf
  - pymc
  - arviz
  - wheel
  - setuptools
  - filelock
  - rich
  - multipledispatch
  - pymc-base
  - pytensor-base
  - pytensor
  - etuples
  - minikanren
  - toolz
  - logical-unification
  - cons
  - typing_extensions
  - xgboost
